# Generated by Django 3.1.2 on 2020-12-16 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menus', '0003_auto_20201215_0013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=250)),
                ('client', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('option', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menus.option')),
            ],
        ),
    ]
