# Generated by Django 3.1.2 on 2020-12-15 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_auto_20201215_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='menu',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='menus.menu'),
        ),
    ]
