# Generated by Django 3.1.2 on 2020-12-16 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0003_auto_20201215_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='unique_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
